In [7]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
# TASK 1: ADVANCED SCALAR & ARRAY OPERATIONS
scalar = 4.3
array = np.array([-4.5, -2.2, 0.8, 1.5, 2.7, 3.6, 5.1, 7.4])
print("\nScalar:", scalar)
print("Array:", array)

print("\n--- Arithmetic Operations ---")

print("Addition with scalar:")
print(array + scalar)

print("\nSubtraction with scalar:")
print(array - scalar)

print("\nMultiplication with scalar:")
print(array * scalar)

print("\nDivision with scalar:")
print(array / scalar)

print("\n--- Mathematical Functions ---")

safe_array = np.abs(array)

print("Square Root:")
print(np.sqrt(safe_array))

print("\nAbsolute Value:")
print(np.abs(array))

print("\nExponential:")
print(np.exp(array))

print("\nNatural Logarithm:")
print(np.log(safe_array))
print("\nLogarithm Base 10:")
print(np.log10(safe_array))

print("\n--- Trigonometric Functions ---")

print("sin():")
print(np.sin(array))

print("\ncos():")
print(np.cos(array))

print("\ntan():")
print(np.tan(array))

clipped_array = np.clip(array, -1, 1)

print("\narcsin() after clipping:")
print(np.arcsin(clipped_array))

print("\narccos() after clipping:")
print(np.arccos(clipped_array))
print("\narctan():")
print(np.arctan(array))



Scalar: 4.3
Array: [-4.5 -2.2  0.8  1.5  2.7  3.6  5.1  7.4]

--- Arithmetic Operations ---
Addition with scalar:
[-0.2  2.1  5.1  5.8  7.   7.9  9.4 11.7]

Subtraction with scalar:
[-8.8 -6.5 -3.5 -2.8 -1.6 -0.7  0.8  3.1]

Multiplication with scalar:
[-19.35  -9.46   3.44   6.45  11.61  15.48  21.93  31.82]

Division with scalar:
[-1.04651163 -0.51162791  0.18604651  0.34883721  0.62790698  0.8372093
  1.18604651  1.72093023]

--- Mathematical Functions ---
Square Root:
[2.12132034 1.4832397  0.89442719 1.22474487 1.64316767 1.8973666
 2.25831796 2.7202941 ]

Absolute Value:
[4.5 2.2 0.8 1.5 2.7 3.6 5.1 7.4]

Exponential:
[1.11089965e-02 1.10803158e-01 2.22554093e+00 4.48168907e+00
 1.48797317e+01 3.65982344e+01 1.64021907e+02 1.63598443e+03]

Natural Logarithm:
[ 1.5040774   0.78845736 -0.22314355  0.40546511  0.99325177  1.28093385
  1.62924054  2.00148   ]

Logarithm Base 10:
[ 0.65321251  0.34242268 -0.09691001  0.17609126  0.43136376  0.5563025
  0.70757018  0.86923172]

--- Tr

In [9]:
# TASK 2: MATRIX MATHEMATICAL OPERATIONS
print("\n" + "=" * 60)
print("TASK 2: MATRIX MATHEMATICAL OPERATIONS")
print("=" * 60)
matrix = np.array([
    [1.2, -2.5, 3.7],
    [-4.1, 5.3, -6.2],
    [2.8, -1.6, 4.5],
    [-3.3, 6.7, -0.9]
])

print("\n4x3 Matrix:")
print(matrix)
print("\n--- Trigonometric Operations ---")

print("sin(matrix):")
print(np.sin(matrix))

print("\ncos(matrix):")
print(np.cos(matrix))

print("\ntan(matrix):")
print(np.tan(matrix))

print("\n--- Inverse Trigonometric Operations ---")

# Clip values to [-1, 1]
clipped_matrix = np.clip(matrix, -1, 1)

print("arcsin(matrix):")
print(np.arcsin(clipped_matrix))

print("\narccos(matrix):")
print(np.arccos(clipped_matrix))

print("\narctan(matrix):")
print(np.arctan(matrix))

print("\n--- Exponential & Logarithmic Operations ---")

safe_matrix = np.abs(matrix)

print("exp(matrix):")
print(np.exp(matrix))

print("\nlog(matrix) using absolute values:")
print(np.log(safe_matrix))

print("\nlog10(matrix) using absolute values:")
print(np.log10(safe_matrix))

print("\n--- Other Mathematical Operations ---")

print("Absolute Value:")
print(np.abs(matrix))

print("\nSquare Root:")
print(np.sqrt(np.abs(matrix)))

print("\nSquare:")
print(np.square(matrix))

print("\nCube Root:")
print(np.cbrt(matrix))

print("\n--- Rounding and Remainder Operations ---")

print("Remainder when divided by 3:")
print(np.mod(matrix, 3))

print("\nRound:")
print(np.round(matrix))

print("\nFloor:")
print(np.floor(matrix))

print("\nCeil:")
print(np.ceil(matrix))



TASK 2: MATRIX MATHEMATICAL OPERATIONS

4x3 Matrix:
[[ 1.2 -2.5  3.7]
 [-4.1  5.3 -6.2]
 [ 2.8 -1.6  4.5]
 [-3.3  6.7 -0.9]]

--- Trigonometric Operations ---
sin(matrix):
[[ 0.93203909 -0.59847214 -0.52983614]
 [ 0.81827711 -0.83226744  0.0830894 ]
 [ 0.33498815 -0.9995736  -0.97753012]
 [ 0.15774569  0.40484992 -0.78332691]]

cos(matrix):
[[ 0.36235775 -0.80114362 -0.84810003]
 [-0.57482395  0.55437434  0.9965421 ]
 [-0.94222234 -0.02919952 -0.2107958 ]
 [-0.98747977  0.91438315  0.62160997]]

tan(matrix):
[[ 2.57215162  0.7470223   0.62473308]
 [-1.42352648 -1.5012734   0.08337771]
 [-0.35552983 34.23253274  4.63733205]
 [-0.15974575  0.44275742 -1.26015822]]

--- Inverse Trigonometric Operations ---
arcsin(matrix):
[[ 1.57079633 -1.57079633  1.57079633]
 [-1.57079633  1.57079633 -1.57079633]
 [ 1.57079633 -1.57079633  1.57079633]
 [-1.57079633  1.57079633 -1.11976951]]

arccos(matrix):
[[0.         3.14159265 0.        ]
 [3.14159265 0.         3.14159265]
 [0.         3.14159265 

In [10]:
# TASK 3: MATRIX STATISTICS AND ANALYSIS
print("\n" + "=" * 60)
print("TASK 3: MATRIX STATISTICS AND ANALYSIS")
print("=" * 60)

np.random.seed(42)

stats_matrix = np.random.uniform(-10, 10, (3, 4))

print("\n3x4 Random Matrix:")
print(stats_matrix)
print("\n--- Basic Statistics ---")

maximum = np.max(stats_matrix)
minimum = np.min(stats_matrix)

max_index = np.unravel_index(
    np.argmax(stats_matrix),
    stats_matrix.shape
)

min_index = np.unravel_index(
    np.argmin(stats_matrix),
    stats_matrix.shape
)
print("Maximum value:", maximum)
print("Minimum value:", minimum)
print("Index position of maximum value:", max_index)
print("Index position of minimum value:", min_index)
print("Sum of all elements:", np.sum(stats_matrix))
print("Product of all elements:", np.prod(stats_matrix))
print("Mean:", np.mean(stats_matrix))
print("Median:", np.median(stats_matrix))
print("Variance:", np.var(stats_matrix))
print("Standard Deviation:", np.std(stats_matrix))
print("\n--- Row and Column Analysis ---")

print("Sum of each row:")
print(np.sum(stats_matrix, axis=1))

print("\nSum of each column:")
print(np.sum(stats_matrix, axis=0))

print("\nMaximum value from each row:")
print(np.max(stats_matrix, axis=1))

print("\nMinimum value from each column:")
print(np.min(stats_matrix, axis=0))
print("\n" + "=" * 60)
print("ALL TASKS COMPLETED SUCCESSFULLY!")
print("=" * 60)


TASK 3: MATRIX STATISTICS AND ANALYSIS

3x4 Random Matrix:
[[-2.50919762  9.01428613  4.63987884  1.97316968]
 [-6.87962719 -6.88010959 -8.83832776  7.32352292]
 [ 2.02230023  4.16145156 -9.58831011  9.39819704]]

--- Basic Statistics ---
Maximum value: 9.398197043239886
Minimum value: -9.588310114083951
Index position of maximum value: (np.int64(2), np.int64(3))
Index position of minimum value: (np.int64(2), np.int64(2))
Sum of all elements: 3.8372341196908994
Product of all elements: -481132597.95689756
Mean: 0.31976950997424164
Median: 1.9977349594024538
Variance: 44.98605419890342
Standard Deviation: 6.707164393311336

--- Row and Column Analysis ---
Sum of each row:
[ 13.11813703 -15.27454163   5.99363872]

Sum of each column:
[ -7.36652458   6.29562809 -13.78675903  18.69488964]

Maximum value from each row:
[9.01428613 7.32352292 9.39819704]

Minimum value from each column:
[-6.87962719 -6.88010959 -9.58831011  1.97316968]

ALL TASKS COMPLETED SUCCESSFULLY!
