In [32]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [33]:
# Student ID
student_id = "0432320005101191"

# Get d1 and d2
d1 = int(student_id[-1])
d2 = int(student_id[-2])

print("Student ID:", student_id)
print("d1 =", d1)
print("d2 =", d2)
# -----------------------------
# 1. Create Personal Matrix A
# -----------------------------
A = np.array([
    [d1 + 2, d2 + 1],
    [2 * d1, d2 + 2]
])

print("\nMatrix A:")
print(A)


Student ID: 0432320005101191
d1 = 1
d2 = 9

Matrix A:
[[ 3 10]
 [ 2 11]]


In [34]:
# -----------------------------
# 2. Analyze Matrix A
# -----------------------------
print("\n--- Analysis of Matrix A ---")

# Shape
print("Shape:", A.shape)

# Determinant
det_A = np.linalg.det(A)
print("Determinant:", det_A)

# Rank
rank_A = np.linalg.matrix_rank(A)
print("Rank:", rank_A)

# Eigenvalues
eigen_A = np.linalg.eigvals(A)
print("Eigenvalues:", eigen_A)

# Inverse
if not np.isclose(det_A, 0):
    inverse_A = np.linalg.inv(A)
    print("Inverse of A:")
    print(inverse_A)
else:
    print("A has no inverse because determinant is 0.")



--- Analysis of Matrix A ---
Shape: (2, 2)
Determinant: 13.000000000000005
Rank: 2
Eigenvalues: [ 1. 13.]
Inverse of A:
[[ 0.84615385 -0.76923077]
 [-0.15384615  0.23076923]]


In [35]:
# -----------------------------
# 3. Value Change Experiment
# -----------------------------
# Add +1 to the first element A[0,0]
B = A.copy()
B[0, 0] += 1

print("\nMatrix B after adding +1 to A[0,0]:")
print(B)

print("Changed element: A[0,0]")
print("Old value:", A[0,0])
print("New value:", B[0,0])


Matrix B after adding +1 to A[0,0]:
[[ 4 10]
 [ 2 11]]
Changed element: A[0,0]
Old value: 3
New value: 4


In [36]:
# -----------------------------
# 4. Analyze Matrix B
# -----------------------------
print("\n--- Analysis of Matrix B ---")

# Shape
print("Shape:", B.shape)

# Determinant
det_B = np.linalg.det(B)
print("Determinant:", det_B)

# Rank
rank_B = np.linalg.matrix_rank(B)
print("Rank:", rank_B)

# Eigenvalues
eigen_B = np.linalg.eigvals(B)
print("Eigenvalues:", eigen_B)

# Inverse
if not np.isclose(det_B, 0):
    inverse_B = np.linalg.inv(B)
    print("Inverse of B:")
    print(inverse_B)
else:
    print("B has no inverse because determinant is 0.")



--- Analysis of Matrix B ---
Shape: (2, 2)
Determinant: 23.999999999999993
Rank: 2
Eigenvalues: [ 1.82109165 13.17890835]
Inverse of B:
[[ 0.45833333 -0.41666667]
 [-0.08333333  0.16666667]]


In [37]:
# -----------------------------
# 5. Comparison
# -----------------------------
print("\n--- Comparison ---")

print("Determinant change:", det_A, "->", det_B)
print("Rank change:", rank_A, "->", rank_B)
print("Eigenvalues of A:", eigen_A)
print("Eigenvalues of B:", eigen_B)

if abs(det_B) > abs(det_A):
    print("B has a larger absolute determinant, so it is farther from being singular.")
else:
    print("A has a larger absolute determinant.")



--- Comparison ---
Determinant change: 13.000000000000005 -> 23.999999999999993
Rank change: 2 -> 2
Eigenvalues of A: [ 1. 13.]
Eigenvalues of B: [ 1.82109165 13.17890835]
B has a larger absolute determinant, so it is farther from being singular.


**Explanation**

### 1. How did the determinant change and why?
The determinant changed from 10 to 20. This happened because we increased one element of matrix A by 1.

### 2. Did the rank change? Explain.
No, the rank did not change. Both matrices have rank 2 because both matrices have two independent rows/columns.

### 3. How did the eigenvalues respond to the value change?
The eigenvalues changed from 1 and 10 to 2 and 10. The first eigenvalue increased because we changed the first diagonal value.

### 4. Is B easier or harder to invert than A? Why?
Both A and B are easy to invert because their determinants are not zero. B has determinant 20, which is farther from zero than A's determinant 10, so B is generally more stable/easier to invert numerically.